// <auto-generated />
using System;
using KuaforRandevuAPI.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuaforRandevuAPI.DataAccess.Migrations
{
    [DbContext(typeof(BarberContext))]
    [Migration("20251228174107_editTimeColumn")]
    partial class editTimeColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KuaforRandevuAPI.Entities.Concrete.Barber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("JobEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("JobStartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Barbers");
                });

            modelBuilder.Entity("KuaforRandevuAPI.Entities.Concrete.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("KuaforRandevuAPI.Entities.Concrete.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ServiceDuration")
                        .HasColumnType("time");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ServicePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("KuaforRandevuAPI.Entities.Concrete.Reservation", b =>
                {
                    b.HasOne("KuaforRandevuAPI.Entities.Concrete.Barber", "Barber")
                        .WithMany("Reservations")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");
                });

            modelBuilder.Entity("KuaforRandevuAPI.Entities.Concrete.Service", b =>
                {
                    b.HasOne("KuaforRandevuAPI.Entities.Concrete.Barber", "Barber")
                        .WithMany("Services")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");
                });

            modelBuilder.Entity("KuaforRandevuAPI.Entities.Concrete.Barber", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
